package es.pln.textsimplification.view;

import es.pln.textsimplification.lexparser.TextSimplification;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jsoup.Jsoup;

/**
 *
 * @author Raúl Moya Reyes <raulmoya.es>
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        txtaOriginal.setLineWrap(true);
        txtaSimplified.setLineWrap(true);
        setIconImage (new ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        jToolBar1 = new javax.swing.JToolBar();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnURL = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExe = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel3 = new javax.swing.JLabel();
        lbPercent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaOriginal = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSimplified = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtaMore = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miOpen = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        miExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Text Simplification");
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/file.png"))); // NOI18N
        btnOpen.setToolTipText("Open documents");
        btnOpen.setBorderPainted(false);
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpen);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/save.png"))); // NOI18N
        btnSave.setToolTipText("Save simplified text");
        btnSave.setBorderPainted(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnURL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/url.png"))); // NOI18N
        btnURL.setFocusable(false);
        btnURL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnURL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnURLActionPerformed(evt);
            }
        });
        jToolBar1.add(btnURL);
        jToolBar1.add(jSeparator1);

        btnExe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/play.png"))); // NOI18N
        btnExe.setToolTipText("Simplify text");
        btnExe.setFocusable(false);
        btnExe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExe.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnExe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExeActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExe);

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/stop.png"))); // NOI18N
        btnClean.setToolTipText("Clean text");
        btnClean.setFocusable(false);
        btnClean.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClean.setMargin(new java.awt.Insets(2, 2, 2, 2));
        btnClean.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClean);
        jToolBar1.add(jSeparator3);

        jLabel3.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        jLabel3.setText("Simplified size: ");
        jToolBar1.add(jLabel3);

        lbPercent.setFont(new java.awt.Font("Droid Sans", 0, 18)); // NOI18N
        lbPercent.setText("0 %");
        jToolBar1.add(lbPercent);

        jLabel1.setText("Original Text");

        txtaOriginal.setColumns(20);
        txtaOriginal.setRows(5);
        txtaOriginal.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtaOriginal);

        jLabel2.setText("Simplified Text");

        txtaSimplified.setColumns(20);
        txtaSimplified.setRows(5);
        txtaSimplified.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtaSimplified);

        txtaMore.setColumns(20);
        txtaMore.setRows(2);
        jScrollPane3.setViewportView(txtaMore);

        jLabel4.setText("More representative words");

        jMenu1.setText("File");

        miOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/ssearch.png"))); // NOI18N
        miOpen.setMnemonic('o');
        miOpen.setText("Open");
        miOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenActionPerformed(evt);
            }
        });
        jMenu1.add(miOpen);

        miSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/ssave.png"))); // NOI18N
        miSave.setMnemonic('s');
        miSave.setText("Save");
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        jMenu1.add(miSave);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/exit.png"))); // NOI18N
        miExit.setMnemonic('e');
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        jMenu1.add(miExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/splay.png"))); // NOI18N
        jMenuItem1.setMnemonic('p');
        jMenuItem1.setText("Simplify");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/sstop.png"))); // NOI18N
        jMenuItem2.setMnemonic('c');
        jMenuItem2.setText("Clean");
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/pln/textsimplification/view/icons/info.png"))); // NOI18N
        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 479, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(660, 557));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenActionPerformed

        String os = System.getProperty("os.name");
        File file;
        String zenity = "zenity --file-selection --title=Open";
        String filestring = null;
        if ((os.contains("nix") || os.contains("nux"))) {
            //Use native Linux file selection.
            try {
                Process p = Runtime.getRuntime().exec(zenity);
                BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
                StringBuilder sb = new StringBuilder();
                String line;
                sb.append(br.readLine());
                filestring = sb.toString();
            } catch (IOException e1) {
                System.out.println("Problem in file");
            }
            file = new File(filestring);
            try {
                txtaOriginal.read(new FileReader(file.getAbsolutePath()), null);
            } catch (IOException ex) {
                System.out.println("Problem accessing file" + file.getAbsolutePath());
            }
        } else {
            int returnVal = jFileChooser1.showOpenDialog(jFrame1);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser1.getSelectedFile();
                try {
                    // What to do with the file, e.g. display it in a TextArea
                    txtaOriginal.read(new FileReader(file.getAbsolutePath()), null);
                } catch (IOException ex) {
                    System.out.println("Problem accessing file" + file.getAbsolutePath());
                }
            } else {
                System.out.println("File access cancelled by user.");
            }
        }

    }//GEN-LAST:event_miOpenActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        miOpenActionPerformed(evt);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnExeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExeActionPerformed
        TextSimplification tsp = new TextSimplification();
        // Añado el filtro de las relaciones que quiero que muestre, se podría hacer mediante interfaz
        String[] relations = {"amod", "tmod", "prep", "comp", "pobj", "num"};
        tsp.simplify(txtaOriginal.getText(), new ArrayList(Arrays.asList(relations)));
        lbPercent.setText(tsp.getSimplifiedText().length() / (float) txtaOriginal.getText().length() * 100 + "%");
        txtaSimplified.setText(tsp.getSimplifiedText());
        txtaMore.setText(tsp.getWordCount());
    }//GEN-LAST:event_btnExeActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        txtaOriginal.setText(null);
        txtaSimplified.setText(null);
    }//GEN-LAST:event_btnCleanActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        miSaveActionPerformed(evt);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed

        String os = System.getProperty("os.name");
        File file;
        String zenity = "zenity --file-selection --title=Save --save --confirm-overwrite";
        String filestring = null;
        if ((os.contains("nix") || os.contains("nux"))) {
            //Use native Linux file selection.
            try {
                Process p = Runtime.getRuntime().exec(zenity);
                BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
                StringBuilder sb = new StringBuilder();
                String line;
                sb.append(br.readLine());
                filestring = sb.toString();
            } catch (IOException e1) {
                System.out.println("Problem in file");
            }
            file = new File(filestring);
            String sb = txtaSimplified.getText();
            try (FileWriter fw = new FileWriter(filestring)) {
                fw.write(sb);
            } catch (IOException ex) {
                System.out.println("Problem to save " + filestring);
            }
        } else {
            String sb = txtaSimplified.getText();
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new File(""));
            int retrival = chooser.showSaveDialog(null);
            if (retrival == JFileChooser.APPROVE_OPTION) {
                try (FileWriter fw = new FileWriter(chooser.getSelectedFile())) {
                    fw.write(sb);
                } catch (IOException ex) {
                    System.out.println("Problem to save " + chooser.getSelectedFile());
                }
            }
        }

    }//GEN-LAST:event_miSaveActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JPanel message = new JPanel(new GridLayout(0, 1));
        message.add(new JLabel("Text Simplification"));
        message.add(new JLabel("Raúl Moya Reyes"));
        message.add(new JLabel("www.raulmoya.es"));
        JOptionPane.showMessageDialog(null, message, "About us", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnURLActionPerformed
        String page = "";
        String iUrl = JOptionPane.showInputDialog(null, "Select a url", "Url", JOptionPane.NO_OPTION);
        try {
            URL url = new URL(iUrl);
            URLConnection yc = url.openConnection();
            try (BufferedReader in = new BufferedReader(new InputStreamReader(yc.getInputStream(),"UTF-8"))) {
                String inputLine;
                while ((inputLine = in.readLine()) != null) {
                    page += inputLine;
                }
                in.close();
            }
        } catch (IOException e) {
            //
        }
        txtaOriginal.setText(Jsoup.parse(page).text());
    }//GEN-LAST:event_btnURLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnExe;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnURL;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbPercent;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miOpen;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JTextArea txtaMore;
    private javax.swing.JTextArea txtaOriginal;
    private javax.swing.JTextArea txtaSimplified;
    // End of variables declaration//GEN-END:variables

}
